[package]
name = "first-unique"
description = "Find first unique word from a large CSV file."
version = "0.1.0"
authors = ["Tzu-Chiao Yeh <su3g4284zo6y7@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.6"
